# trusty beta image has jdk8, gcc4.8.4
dist: trusty
sudo: required
osx_image: xcode9.4
language: python

os:
  - linux
  - osx

git:
  depth: 3
  quiet: true

python:
  - "3.7-dev"

before_install:
  - ./tools/get-bazel.sh "${TRAVIS_OS_NAME}"

script:
  - ./tools/run-bazel.sh //...
