# trusty beta image has jdk8, gcc4.8.4
dist: trusty
sudo: required
osx_image: xcode9.4
language: python
env:
  - PYTHON=3.7-dev

matrix:
  include:
    - os: linux
      python: 3.7-dev
      language: python
    - os: osx
      language: generic

git:
  depth: 3
  quiet: true

before_install:
  - ./tools/setup-travis.sh "${TRAVIS_OS_NAME}"
  - ./tools/get-bazel.sh "${TRAVIS_OS_NAME}"

script:
  - ./tools/run-bazel.sh //...
