# trusty beta image has jdk8, gcc4.8.4
dist: trusty
sudo: required
osx_image: xcode9.4
# Not technically required but suppresses 'Ruby' in Job status message.
language: java

os:
  - linux
  - osx

before_install:
  - ./tools/get-bazel.sh "${TRAVIS_OS_NAME}"

script:
  - ./tools/run-bazel.sh //...
