language: minimal
dist: xenial
sudo: true
os:
  - linux
git:
  depth: 3
  quiet: true

before_install:
  - ./tools/install-travis.sh "$HOME/bin"

script:
  - ./tools/run-travis.sh "$HOME/bin" //...

notifications:
  email: false
