language: python
python: "3.7"
dist: xenial
sudo: true
os:
  - linux
git:
  depth: 3
  quiet: true

before_install:
  - export PATH="$HOME/bin:$PATH"
  - ./tools/get-bazel.sh "$HOME/bin/bazel"
  - ln -s "$(command -v python2)" "$HOME/bin/python"

script:
  - ./tools/run-bazel.sh "$HOME/bin/bazel" //...
