# (Github Light Colorblind) Colors for Alacritty

# Default colors
[colors.primary]
background = "0xffffff"
foreground = "0x24292f"

# Cursor colors
#
# These will only be used when the `custom_cursor_colors` field is set to `true`.
[colors.cursor]
text = "0xffffff"
cursor = "0x24292f"

# Normal colors
[colors.normal]
black = "0x24292f"
red = "0xb35900"
green = "0x0550ae"
yellow = "0x4d2d00"
blue = "0x0969da"
magenta = "0x8250df"
cyan = "0x1b7c83"
white = "0x6e7781"

# Bright colors
[colors.bright]
black = "0x57606a"
red = "0x8a4600"
green = "0x0969da"
yellow = "0x633c01"
blue = "0x218bff"
magenta = "0x8250df"
cyan = "0x1b7c83"
white = "0x6e7781"