[general]
import = [
  "~/.config/alacritty/themes/theme.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[env]
#TERM = "xterm"
SHELL = "/bin/zsh"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 14.0

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 0
multiplier = 3

[terminal]
osc52 = "CopyPaste"
shell = { program = "/bin/zsh", args = ["-l"] }

[window]
decorations = "None"
opacity = 1.0
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "Key1"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "Key2"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "Key3"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "Key4"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "Key5"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "Key6"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "Key7"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "Key8"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "Key9"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "LBracket"
mods = "Command|Shift"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "RBracket"
mods = "Command|Shift"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "T"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "J"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "K"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "H"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "L"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "F"
mods = "Command"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "V"
mods = "Command|Shift"
command = { program = "/bin/sh", args = ["-c", "$HOME/.local/bin/scpaste"] }

[[keyboard.bindings]]
key = "W"
mods = "Command|Shift"
action = "Quit"
